sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/debian-stretch.base.nim.ui
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/debian-stretch.base.nim.ui run "nimble install -y && nimble test"
